Remove unused constant
Removing obsolete const mon_names, because its usage has been removed
and this causes now a gcc warning/error:
error: 'mon_names' defined but not used [-Werror=unused-const-variable=]

Signed-off-by: Juergen Kosel <juergen.kosel@gmx.de>